---
- name: Create a "kubernetes" repo 
  copy:
    dest: /etc/yum.repos.d/
    src: kubernetes.repo
    mode: 644
  tags: minikube

- name: configure and activate the "bridge-nf-call-iptables" kernel parameter
  lineinfile:
    path: /etc/sysctl.d/92-k8s-bridge-nf-call-iptables.conf
    line: "net.bridge.bridge-nf-call-{{ item }} = 1"
    state: present
    create: True
  loop:
    - "iptables"
    - "ip6tables"

- name: ... and activate the kernel parameter
  command: sysctl -p
# changed_when: False

- name: Install kubectl
  yum:
    name:
      - kubectl
      - kubelet
      - ebtables
      - socat
      - conntrack-tools
    state: present
  tags: minikube

- name: Install minikube
  yum:
    name:
      - https://storage.googleapis.com/minikube/releases/latest/minikube-1.5.2.rpm
    state: present
  tags: minikube

- name: avoid installing a nested VM by making this a "bare metal" installation
  command: minikube config set vm-driver none

- name: ensure the kubelet service is enabled
  service:
    name: kubelet
    enabled: True


