---
- name : Play 01 - setup
  hosts: gcpsdk
  become: True
  gather_facts: True

  tasks:
    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 300
      failed_when: False
      changed_when: False

    - name: execute "roles" playbooks
      include_role:
        name: "{{ mk_role }}"
      loop:
          - roles/docker
          - roles/users
      loop_control:
        loop_var: mk_role


