---
- name : Docker Play
  hosts: gcpsdk
  become: True
  gather_facts: True

  tasks:
    - include_role:
        name: "{{ my_role }}"
      loop:
          - roles/docker
      loop_control:
        loop_var: my_role


