---
- name : Play 00 - setup
  hosts: some-hosts
  become: False
  gather_facts: False

  tasks:
      - setup:
          filter: "ansible_date_time"
        run_once: True
        delegate_to: 127.0.0.1

      - set_fact:
          info_out_dir: "output-{{ ansible_date_time.iso8601 | regex_replace('\\:', '-') }}"

      - set_fact:
          mem_dir: "{{ info_out_dir }}/mem"
          ps_out_dir: "{{ info_out_dir }}/jvms"
          sysctl_out_dir: "{{ info_out_dir }}/sysctl_out"
        run_once: True
        delegate_to: 127.0.0.1

      - file:
          path: "{{ item }}"
          state: directory
        with_items:
            - "{{ info_out_dir }}"
            - "{{ mem_dir }}"
            - "{{ ps_out_dir }}"
            - "{{ sysctl_out_dir }}"
        run_once: True
        delegate_to: 127.0.0.1


- name: Play 01 - raw install of python2
  hosts: some-hosts
  remote_user: centos
  become_user: root
  become: True
  gather_facts: no

  roles:
      - {role: "raw_deps" , become: True, remote_user: "centos", become_user: "root", gather_facts: no, }


- name: Play 02 - Base OS config
  hosts: openproject
  remote_user: centos
  become_user: root
  become: True
  gather_facts: yes

  vars_files:
      - ./vars/ocp-userlist.yml
  vars:
      fqdn: '.etocp.interac.int'

  tasks:
      - name: execute "roles" playbooks
        include_role:
          name: "{{ dd_role }}"
        loop:
            - baseos
            - docker
#           - docker_stroage
            - users
        loop_control:
          loop_var: dd_role


  roles:
      - {role: "baseos" , become: True, remote_user: "centos", become_user: "root", gather_facts: yes }


- name: Play 2
  hosts: localhost
  gather_facts: False

  tasks:
      - debug:
          msg: "second message"

      - meta: end_play

