---
- name : Play Provisioning 00 - timestamp setup if / when needed 
  hosts: localhost
  connection: local
  become: False
  gather_facts: False

  tasks:
    - setup:
        filter: "ansible_date_time"
      run_once: True
    - set_fact:
        timestamp: "{{ ansible_date_time.iso8601 | regex_replace('\\:', '-') }}"

- name : Play Provisioning 01 - actual OS-level Config
  hosts: gcpsdk
  become: True
  gather_facts: True

  tasks:
#   - name: execute "roles" playbooks
    - include_role:
        name: "{{ my_role }}"
      loop:
        - roles/provision
      loop_control:
        loop_var: my_role


