---
- name : Users creation Play
  hosts: gcpsdk
  become: True
  gather_facts: True

  tasks:
#   - name: add users
    - include_role:
        name: "{{ my_role }}"
      loop:
          - roles/users
      loop_control:
        loop_var: my_role


