---
- name: fix-ssh | Prepare sshd to accept password based authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: EOF
    regexp:  '^\s*PasswordAuthentication\s+yes'
    line:    'PasswordAuthentication yes'
    state: present
  register: pwd_auth

- name: fix-ssh | Prevent sshd from trying to reverse-resolve host addresses to names
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: EOF
    regexp:  '^\s*UseDNS\s+no'
    line:    'UseDNS no'
    state: present
  register: use_dns


