---
- name: NO IPv6 | Disable IPv6
  copy:
      content: "net.ipv6.conf.all.disable_ipv6 = 1"
      dest: /etc/sysctl.d/99-noipv6.conf
  tags: noipv6

- name: NO IPv6 | Comment-out IPv6 settings on interface
  replace:
    regexp: '^IPV6'
    replace: '#IPV6'
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ansible_default_ipv4.alias}}
  tags: noipv6

- name: NO IPv6 | Coerce sshd to listen on IPv4 only
  replace:
    regexp: '^\s*#\s*AddressFamily\s*any'
    replace:   'AddressFamily inet'
    dest: /etc/ssh/sshd_config
# notify: restart sshd
  tags: noipv6

#   - name: NO IPv6 | Coerce postfix to listen on IPv4 only
#     replace:
#       regexp: '^\s*inet_protocols\s*=\s*all'
#       replace:   '#dd# inet_protocols = all'
#       dest: /etc/postfix/main.cf
#     notify: restart postfix
#     tags: noipv6

- name: NO IPv6 | Convince chrony - if installed - to listen on IPv4 only
  copy:
    force:          yes
    dest:           "/etc/sysconfig/chronyd"
    content:        "OPTIONS=\"-4\"\n"
# notify:  restart chronyd
  when: >
    chrony_syscfg.stat.exists is defined
    and chrony_syscfg.stat.exists
    and ansible_os_family == "RedHat"
    and  ansible_distribution_major_version|int >= 7
  tags: noipv6

#- name: Adjust /etc/hosts
#  lineinfile:
#    line: "inet_protocols = ipv4"
#    insertafter: 'inet_protocols = all'
#    state:  present
#    dest: /etc/postfix/main.cf



