---
- name: include storage prep
  include_tasks: dck-ce-storage-setup.yml

- name: create the "Docker Engine Comunity Edition" repo
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: "/etc/yum.repos.d/docker-ce.repo"

- name: configure and activate the "bridge-nf-call-iptables" kernel parameter
  lineinfile:
    path: /etc/sysctl.d/92-bridge-nf-call-iptables.conf
    line: "net.bridge.bridge-nf-call-{{ item }} = 1"
    state: present
    create: True
  loop:
    - "iptables"
    - "ip6tables"

- name: install Docker-CE and auxiliary...
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: directory "/etc/docker"
  file:
    path: /etc/docker
    state: directory

- name: create the "daemon.json" for Docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    force: True

- name: ... and make sure the service is enabled & started
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - docker
  tags: docker


