---
- name: Create groups
  group:
    state: present
    name: "docker"
    gid: "2200"
 
- name: Install Docker form the distro repos for Fedora (Docker release 13, I think ?)
  include_tasks: docker-rh-repo.yml
  when:
    ansible_os_family == "RedHat" and ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 29
  tags: fedora

- name: Install Docker-CE on RHEL or CentOS 7+
  include_tasks: docker-ce.yml
  when:
    ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution_major_version|int >= 7
  tags: rhel7

- name: In case none of the above, we give up 
  debug:
    msg: "EXIT !"
- meta: end_play


