---
- name : Play 01 - setup
  hosts: minikube
  become: True
  gather_facts: True

  tasks:
    - name: execute "roles" playbooks
      include_role:
        name: "{{ mk_role }}"
      loop:
          - roles/minikube
      loop_control:
        loop_var: mk_role


