---
- name : Play 01 - Wait for Reboot
  hosts: minikube
  become: True
  gather_facts: False

  tasks:
    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 300
      failed_when: False
      changed_when: False


