---
#- name: Prepare the OveralyFS2 configuration file, for docker
#  copy:
#    dest: /etc/sysconfig/docker-storage-setup
#    src: docker-storage-setup
#    mode: 644
#  tags: docker

- name: Create groups
  group:
    state: present
    name: "docker"
    gid: "2200"
 
- name: include storage prep
  include_tasks: dck-ce-storage-setup.yml
 

#- name: Install Docker
#  yum:
#    name:
#      - docker
#    state: present
#  tags: docker

- name: create the "Docker Engine Comunity" repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#   name: "docker-ce"
#   file: https://download.docker.com/linux/centos/docker-ce.repo
#   state: present

- name: install Docker-CE and auxiliary...
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
#     - lvm2
    state: present

- name: directory "/etc/docker"
  file:
    path: /etc/docker
    state: directory

- name: create the "daemon.json" for Docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    force: True

- name: ... and the services are active - RHEL 6.x speciffic
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - docker
  tags: docker

